
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
    reviewers:
      - "simplereport-staticsitereviewers"
      - "alixmx"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
    reviewers:
      - "simplereport-staticsitereviewers"
      - "alixmx"

  - package-ecosystem: "bundler"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
    reviewers:
      - "simplereport-staticsitereviewers"
      - "alixmx"
