env:
  browser: true
  commonjs: true
  es2020: true
  es6: true,
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 11
ignorePatterns:
  - uswds.min.js
  - uswds-init*.js
  - gtm.js
  - main.js
  - uswds.js
  - jquery3.5.1.min.js
  - url-search-param-polyfil.js
  - anchor.min.js
  - touchpoints.js
rules: {}
plugins:
  - frontmatter
