url: https://stg.simplereport.gov
okta_url: https://hhs-prime.okta.com/oauth2/default/v1/authorize?client_id=0oa62qncijWSeQMuc4h6&redirect_uri=https://stg.simplereport.gov/app&response_type=token+id_token&scope=openid%20simple_report%20simple_report_stg&nonce=thisisnotsafe&state=thisisbogus
