name: Check Link Continuity (Creates Issues)

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * 0"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.6.0
        with:
          # Check SimpleReport
          args: "--verbose --no-progress 'https://simplereport.gov'"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: Design, Content design
