name: Deploy to training

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy static landing page
        run: npm run deploy-azure-training
      - name: Purge CDN
        run: az cdn endpoint purge --resource-group prime-simple-report-training --profile-name simple-report-training --name simple-report-training --content-paths "/*" --no-wait
