name: Lighthouse

on: pull_request

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Cache npm local files
        uses: actions/cache@v4.2.3
        with:
          path: |
            ./node_modules
          key: npm-${{matrix.node}}-${{ hashFiles('yarn.lock', 'package.json') }}
      - name: Install node modules
        run: npm install
      - name: Setup site
        run: |
          npm run setup
      - name: Serve site
        run: bundle exec jekyll serve &
      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            $SITE_URL/
          uploadArtifacts: true
          configPath: ./lighthouse/lighthouserc.yml
          runs: 1
        env:
          SITE_URL: http://localhost:4000
