name: Rubocop

on: pull_request

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install rubocop
        run: gem install rubocop
      - name: Run rubocop
        run: rubocop
